Added PERMISSIONS.MD file
RootstockCollective/collective-rewards-sc pull request #133
Opened 2024-12-18 23:17 UTC by bezerrablockchain

## What

- Added a Permissions file with info about permissions defined for the `GovernanceManagerRootstockCollective` contract

## Why

- For getting a more clear vision about what need to set or use to call this contract functions

## Refs

- https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267?selectedIssue=TOK-265

2024-12-20 09:13 UTC, antomor commented on docs/src/src/PERMISSIONS.md
I'd move this file into a spec folder, as in #130.

2024-12-20 09:14 UTC, antomor commented on docs/src/src/PERMISSIONS.md
> +-- View validation of their role using `validateGovernor`.
I think that `--` is not rendered as expected, see [here](https://github.com/RootstockCollective/collective-rewards-sc/blob/tok-265/permissions-doc-gov/docs/src/src/PERMISSIONS.md)

2024-12-20 09:18 UTC, antomor commented on docs/src/src/PERMISSIONS.md
> +### KYC Approver
I'd try to be more specific here listing all the operations that the KYC approver can execute in the `BuilderRegistry` for instance

2024-12-20 09:20 UTC, antomor commented on docs/src/src/PERMISSIONS.md
> +### Foundation Treasury
Same here, if you check where the `validateFoundationTreasury` is used, you will have a list of operations

2024-12-20 09:22 UTC, antomor requested changes
@bezerrablockchain thank you for the changes. I'd try to be more specific about what each role can do, referring to the related functions of the other contracts. As a general comment, it's not clear to me the distinction among abilities, permissions list and capabilities.

2024-12-28 00:59 UTC, bezerrablockchain commented on docs/src/src/PERMISSIONS.md
@antomor sorry, I didnt find any SPEC folder, should I create one?

2024-12-28 00:59 UTC, bezerrablockchain commented on docs/src/src/PERMISSIONS.md
> +-- View validation of their role using `validateGovernor`.
Fixed

2024-12-28 00:59 UTC, bezerrablockchain commented on docs/src/src/PERMISSIONS.md
> +### KYC Approver
Added a new section specific for this contract

2024-12-28 01:00 UTC, bezerrablockchain commented on docs/src/src/PERMISSIONS.md
> +### Foundation Treasury
Added a new section specific for the `BuilderRegistry`

2024-12-30 17:39 UTC, jmendiola222 commented on docs/src/src/PERMISSIONS.md
Here: https://github.com/RootstockCollective/collective-rewards-sc/tree/main/specs

2025-01-02 19:40 UTC, DinizSa commented on specs/PERMISSIONS.md
> +    + View validation of their role using `validateGovernor`.
Being able to call `validateGovernor` is not specific to any role. Should it be here?

2025-01-02 20:35 UTC, DinizSa commented on specs/PERMISSIONS.md
> +# GovernanceManagerRootstockCollective.sol
`GovernanceManagerRootstockCollective` is used to hold addresses with permissions, then others contracts use those permissions.
 There are other contracts that use these permissions and are not in this list, like `BackersManagerRootstockCollective`. Should all those contracts also be present in this document?

2025-01-02 20:37 UTC, DinizSa commented on specs/PERMISSIONS.md
> +- `NewCycleDurationScheduled(uint256 newCycleDuration_, uint256 cooldownEndTime_)`
is this event relevant here? same applies to other `BuilderRegistryRootstockCollective` events

2025-01-02 21:37 UTC, bezerrablockchain commented on specs/PERMISSIONS.md
> +    + View validation of their role using `validateGovernor`.
Its just a mention that is possible to verfify if an account is the governor by calling this external function

2025-01-02 21:41 UTC, bezerrablockchain commented on specs/PERMISSIONS.md
> +- `NewCycleDurationScheduled(uint256 newCycleDuration_, uint256 cooldownEndTime_)`
I think is not mandatory, if other people also thinks its not relevant I can remove it.

2025-01-02 21:45 UTC, bezerrablockchain commented on specs/PERMISSIONS.md
> +# GovernanceManagerRootstockCollective.sol
Hummm, maybe a good idea.  My first tough was to cover only the `BuilderRegistryRootstockCollective` as the roles are in fact here, instead of `BackersManagerRootstockCollective`

2025-01-02 23:21 UTC, DinizSa commented on specs/PERMISSIONS.md
> +# GovernanceManagerRootstockCollective.sol
Sorry, a fix to my comment: `BackersManagerRootstockCollective` does not use permissions.
A better example would be `RewardDistributorRootstockCollective`, that uses the `foundation` address stored in the `GovernanceManagerRootstockCollective` (ie. to set the permissions for the `sendRewards` method).

2025-01-02 23:26 UTC, DinizSa commented on specs/PERMISSIONS.md
> +    + View validation of their role using `validateGovernor`.
does not seem to fit the section `permissions and capabilities`, that would describe what the role can do. I see methods such as `validateGovernor` as implementation details that do not need to be here. wdyt?

2025-01-02 23:32 UTC, DinizSa commented on specs/PERMISSIONS.md
> +# GovernanceManagerRootstockCollective.sol
I find [velodrome approach](https://github.com/velodrome-finance/contracts/blob/main/PERMISSIONS.md#permissions-list) nice, as they list all the contracts, roles used in that contract, and list of things the role can do in that contract.

2025-01-02 23:52 UTC, bezerrablockchain commented on specs/PERMISSIONS.md
> +# GovernanceManagerRootstockCollective.sol
Sure, I am adding this.  I am also adding Gauge as well

2025-01-17 14:10 UTC, antomor commented on specs/PERMISSIONS.md
> +- `NewCycleDurationScheduled(uint256 newCycleDuration_, uint256 cooldownEndTime_)`
being the file called permissions, I'd remove the events part since may be out of scope.

2025-01-17 14:11 UTC, antomor commented on specs/PERMISSIONS.md
> +    + View validation of their role using `validateGovernor`.
if I read it without checking the code, it looks like only the `governor` can call `validateGovernor`.

2025-01-17 15:30 UTC, bezerrablockchain commented on specs/PERMISSIONS.md
> +    + View validation of their role using `validateGovernor`.
I rephrased it to express a more clear capability

2025-01-17 15:31 UTC, bezerrablockchain commented on specs/PERMISSIONS.md
> +- `NewCycleDurationScheduled(uint256 newCycleDuration_, uint256 cooldownEndTime_)`
I agree as wekk and as we have a consensus here, I am removing those sections from doc

2025-01-20 09:32 UTC, merged